#default settings
server:
  port: 7050
  error:
    include-message: always

spring:
  #database config properties
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #rabbitmq config properties
  rabbitmq:
    host: localhost
    username: user
    password: user
    port: 5672
    template:
      exchange: direct-exchanges


  #rabbitmq dynamic path settings
user-queue:
  name: user-queue
saleAdvertisement-queue:
  name: sale-advertisement-queue


# swagger-ui custom path
# http://localhost:7050/swagger-ui/index.html

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#logging settings
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
